// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) AS count FROM categories
WHERE ($1::text IS NULL OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountCategories(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (id, name, "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4)
RETURNING id, name, "createdAt", "updatedAt"
`

type CreateCategoryParams struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

// SQLC query definitions for category CRUD operations.
// Column names follow the PostgreSQL schema: id, name, "createdAt", "updatedAt".
// All queries use parameterized placeholders ($1, $2, ...) for SQL injection safety.
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const existsCategoryByName = `-- name: ExistsCategoryByName :one
SELECT EXISTS(SELECT 1 FROM categories WHERE name = $1 AND id != $2) AS "exists"
`

type ExistsCategoryByNameParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) ExistsCategoryByName(ctx context.Context, arg ExistsCategoryByNameParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsCategoryByName, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findAllCategories = `-- name: FindAllCategories :many
SELECT id, name, "createdAt", "updatedAt"
FROM categories
WHERE ($1::text IS NULL OR name ILIKE '%' || $1 || '%')
ORDER BY
  CASE WHEN $2 = 'name' AND $3 = 'asc' THEN name END ASC,
  CASE WHEN $2 = 'name' AND $3 = 'desc' THEN name END DESC,
  CASE WHEN $2 = 'createdAt' AND $3 = 'asc' THEN "createdAt" END ASC,
  CASE WHEN $2 = 'createdAt' AND $3 = 'desc' THEN "createdAt" END DESC
LIMIT $4 OFFSET $5
`

type FindAllCategoriesParams struct {
	Column1 string
	Column2 interface{}
	Column3 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) FindAllCategories(ctx context.Context, arg FindAllCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, findAllCategories,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCategoryByID = `-- name: FindCategoryByID :one
SELECT id, name, "createdAt", "updatedAt"
FROM categories
WHERE id = $1
`

func (q *Queries) FindCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $1, "updatedAt" = $2
WHERE id = $3
RETURNING id, name, "createdAt", "updatedAt"
`

type UpdateCategoryParams struct {
	Name      string
	UpdatedAt int64
	ID        pgtype.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.UpdatedAt, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
