// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AtlasSchemaRevisionsAtlasSchemaRevision struct {
	Version         string
	Description     string
	Type            int64
	Applied         int64
	Total           int64
	ExecutedAt      pgtype.Timestamptz
	ExecutionTime   int64
	Error           pgtype.Text
	ErrorStmt       pgtype.Text
	Hash            string
	PartialHashes   []byte
	OperatorVersion string
}

type Attribute struct {
	ID          pgtype.UUID
	CategoryId  pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   int64
	UpdatedAt   int64
}

type AttributesItem struct {
	CategoryId  pgtype.UUID
	AttributeId pgtype.UUID
	ItemId      pgtype.UUID
}

type Category struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

type Item struct {
	ID          pgtype.UUID
	CategoryId  pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   int64
	UpdatedAt   int64
}

type VAttribute struct {
	ID          pgtype.UUID
	CategoryId  pgtype.UUID
	Name        string
	Description pgtype.Text
}

type VCategory struct {
	ID   pgtype.UUID
	Name string
}

type VItem struct {
	ID          pgtype.UUID
	CategoryId  pgtype.UUID
	Name        string
	Description pgtype.Text
}
